package constants

const (
	UsedCondoName           = "物件名"
	PriceText               = "価格"
	Layout                  = "間取り"
	TotalUnitsText          = "総戸数"
	OccupiedAreaText        = "専有面積"
	OtherAreaText           = "その他面積"
	BuiltAt                 = "完成時期（築年月）"
	Address                 = "住所"
	Transportation          = "交通"
	SalesSchedule           = "販売スケジュール"
	EventInfo               = "イベント情報"
	MostPriceRange          = "最多価格帯"
	MaintenanceFee          = "管理費"
	RepairReserveFund       = "修繕積立金"
	IntialRepairReserveFund = "修繕積立基金"
	AdditionalCosts         = "諸費用"
	Floor                   = "所在階"
	Direction               = "向き"
	EnergyEfficiency        = "エネルギー消費性能"
	InsulationPerformance   = "断熱性能"
	EstimatedUtilityCost    = "目安光熱費"
	Reform                  = "リフォーム"
	Structure               = "構造・階建て"
	SiteArea                = "敷地面積"
	LandRight               = "敷地の権利形態"
	Zoning                  = "用途地域"
	Parking                 = "駐車場"
	Contractor              = "施工"
)
